title: Frekyll
email: josh@frekyll.com
description: Frekyll is a digital designer and musician
baseurl: ""
url: "http://frekyll.com"

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
